wiki/wiki/encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry"),
    path("search/<str:search>", views.search, name="search"),
    path("new/page", views.new, name="new"),
    path("edit/<str:edit>", views.edit, name="edit"),
    path("random/page", views.random, name="random")
]

wiki/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls")),
]

wiki/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

wiki/wiki/encyclopedia/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from random import randrange
import markdown2

from . import util

def edit(request, edit):
    if request.method == "POST":
        content = request.POST.get("new_content")
        util.save_entry(edit, content)
        return HttpResponseRedirect("/wiki/" + edit)
    f = util.get_entry(edit)
    return render(request, "encyclopedia/edit.html", {
        "title": edit,
        "content": f
    })


def entry(request, title):
    if util.get_entry(title) == None:
        return HttpResponse("Error page not found")
    f = markdown2.markdown(util.get_entry(title))
    return render(request, "encyclopedia/entry.html", {
        "content": f,
        "title": title
    })
    

def index(request):
    if request.method == "POST":
        search = str(request.POST.get("q")).lower()
        entries = util.list_entries()
        entries = [x.lower() for x in entries]
        if search in entries:
            return HttpResponseRedirect("/wiki/" + search)
        return HttpResponseRedirect("/wiki/search/" + search)       
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def new(request):
    if request.method == "POST":
        title = request.POST.get("new_title")
        content = request.POST.get("new_content")
        entries = util.list_entries()
        entries = [x.lower() for x in entries]
        if title.lower() in entries:
            return HttpResponse("Error entry already exists")
        util.save_entry(title, content)
        return HttpResponseRedirect("/wiki")
    return render(request, "encyclopedia/new.html")


def random(request):
    entries = util.list_entries()
    i = randrange(len(entries))
    return HttpResponseRedirect("/wiki/" + entries[i])


def search(request, search):
    return render(request, "encyclopedia/search.html", {
        "entries": util.list_entries(),
        "search": search
    })

wiki/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>Edit Page</h1>
    <form action="{% url 'wiki:edit' title %}" method="post">
        {% csrf_token %}
        <div>Title: {{ title }}</div>
        <textarea id="new_content" name="new_content" rows="5" cols="50">{{ content }}</textarea>
        <br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    {{ content|safe }}
    <a href="{% url 'wiki:edit' title %}">Edit</a>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{{ entry }}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'wiki:index' %}" method="post">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'wiki:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'wiki:new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'wiki:random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

wiki/wiki/encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>New Page</h1>
    <form action="{% url 'wiki:new' %}" method="post">
        {% csrf_token %}
        <input type="text" placeholder="Enter a title" name="new_title"><br>
        <textarea id="new_content" name="new_content" rows="5" cols="50" placeholder="Type in the Markdown content for the page."></textarea>
        <br>
        <input type="submit" value="Save">
    </form>
{% endblock %}

wiki/wiki/encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages with {{ search }}</h1>

    <ul>
        {% for entry in entries %}
        {% if search|lower in entry|lower %}
            <li><a href="{% url 'wiki:entry' entry %}">{{ entry }}</a></li>
        {% endif %}
        {% endfor %}
    </ul>

{% endblock %}